name: Create Release Demo - GitHub Action
on:
  workflow_dispatch
jobs:
  Create-Release-Demo:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: philippe-patenaude/lpak@a58f1cae3fe5521299a8b86efd8781de88c8b7b6
        with:
          RELEASE_VERSION: 0.0.8
          GAME_NAME: lpak-example
          GAME_DIR: example-project/
